# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectShareiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectShareiOS
  pod 'Parse'
  pod 'AlamofireImage'

  target 'ProjectShareiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectShareiOSUITests' do
    # Pods for testing
  end

end
